/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexoes.MySQL;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class AddingUserScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddingUserScreen
     */
    public AddingUserScreen() {
        initComponents();
    }
    
    MySQL conectar = new MySQL("localhost:3306","brunoac2","root","123mudar");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserCreate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCriarUsuario = new javax.swing.JToggleButton();
        txtSenhaCreate = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtUserCreate.setBackground(new java.awt.Color(204, 204, 204));
        txtUserCreate.setBorder(null);
        jPanel1.add(txtUserCreate);
        txtUserCreate.setBounds(170, 90, 200, 30);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 70, 70, 16);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Senha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 160, 37, 16);

        btnCriarUsuario.setBackground(new java.awt.Color(0, 255, 0));
        btnCriarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarUsuario.setText("Criar");
        btnCriarUsuario.setBorder(null);
        btnCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCriarUsuario);
        btnCriarUsuario.setBounds(140, 250, 270, 40);

        txtSenhaCreate.setBackground(new java.awt.Color(204, 204, 204));
        txtSenhaCreate.setForeground(new java.awt.Color(0, 0, 0));
        txtSenhaCreate.setBorder(null);
        jPanel1.add(txtSenhaCreate);
        txtSenhaCreate.setBounds(170, 180, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarUsuarioActionPerformed
        this.conectar.conectaBanco();
        
        if(txtSenhaCreate.getText().length() == 0 || txtUserCreate.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Error ! Verifique os dados inseridos",
            "ERR!", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            try {
                 this.conectar.insertSQL("INSERT INTO usuarios values("+null+",'"+txtUserCreate.getText()+"','"
                    +txtSenhaCreate.getText()+"');");
                
                JOptionPane.showMessageDialog (null, "Cadastrado com sucesso", "Novo Funcionario", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error ! Verifique os dados inseridos",
                "ERR!", JOptionPane.ERROR_MESSAGE);
            } finally {
            }
        }
    }//GEN-LAST:event_btnCriarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingUserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCriarUsuario;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtSenhaCreate;
    private javax.swing.JTextField txtUserCreate;
    // End of variables declaration//GEN-END:variables
}
