/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexoes.MySQL;
import javax.swing.JOptionPane;
import objetos.Funcionario;

/**
 *
 * @author gabri
 */
public class EditFuncScreen extends javax.swing.JFrame {

    /**
     * Creates new form EditFuncScreen
     */
    public EditFuncScreen() {
        initComponents();
    }
    
    MySQL conectar = new MySQL("localhost:3306","brunoac2","root","123mudar");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFuncNome4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFuncNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtFuncNomeEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFuncCPFEdit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFuncNome2 = new javax.swing.JTextField();
        txtFuncEmailEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFuncCargoEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFuncSalarioEdit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNomeFuncEdit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCpfFuncEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmailFuncEdit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCargoFuncEdit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSalarioFuncEdit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnUpdateFunc = new javax.swing.JToggleButton();
        btnDeleteFunc = new javax.swing.JToggleButton();

        txtFuncNome4.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncNome4.setBorder(null);
        txtFuncNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncNome4ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nome");

        txtFuncNome.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncNome.setBorder(null);
        txtFuncNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncNomeActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nome");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(0, 255, 0));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Salvar alteração");
        jToggleButton1.setBorder(null);
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(322, 269, 164, 35);

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("Apagar funcionario");
        jToggleButton2.setBorder(null);
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(96, 269, 164, 35);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 49, 16);

        txtFuncNomeEdit.setEditable(false);
        txtFuncNomeEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncNomeEdit.setBorder(null);
        txtFuncNomeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncNomeEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncNomeEdit);
        txtFuncNomeEdit.setBounds(40, 60, 200, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CPF");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 49, 16);

        txtFuncCPFEdit.setEditable(false);
        txtFuncCPFEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncCPFEdit.setBorder(null);
        txtFuncCPFEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncCPFEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncCPFEdit);
        txtFuncCPFEdit.setBounds(40, 120, 200, 30);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 49, 16);

        txtFuncNome2.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncNome2.setBorder(null);
        txtFuncNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncNome2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncNome2);
        txtFuncNome2.setBounds(40, 60, 200, 30);

        txtFuncEmailEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncEmailEdit.setBorder(null);
        txtFuncEmailEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncEmailEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncEmailEdit);
        txtFuncEmailEdit.setBounds(40, 180, 200, 30);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 49, 16);

        txtFuncCargoEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncCargoEdit.setBorder(null);
        txtFuncCargoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncCargoEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncCargoEdit);
        txtFuncCargoEdit.setBounds(310, 60, 200, 30);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cargo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 40, 49, 16);

        txtFuncSalarioEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncSalarioEdit.setBorder(null);
        txtFuncSalarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncSalarioEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncSalarioEdit);
        txtFuncSalarioEdit.setBounds(310, 120, 200, 30);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Salario");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 100, 49, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 320);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        txtNomeFuncEdit.setEditable(false);
        txtNomeFuncEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeFuncEdit.setBorder(null);
        txtNomeFuncEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncEditActionPerformed(evt);
            }
        });
        jPanel3.add(txtNomeFuncEdit);
        txtNomeFuncEdit.setBounds(130, 110, 200, 30);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nome");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(130, 90, 37, 16);

        txtCpfFuncEdit.setEditable(false);
        txtCpfFuncEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtCpfFuncEdit.setBorder(null);
        txtCpfFuncEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfFuncEditActionPerformed(evt);
            }
        });
        jPanel3.add(txtCpfFuncEdit);
        txtCpfFuncEdit.setBounds(130, 170, 200, 30);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cpf");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(130, 150, 37, 16);

        txtEmailFuncEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailFuncEdit.setBorder(null);
        txtEmailFuncEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFuncEditActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmailFuncEdit);
        txtEmailFuncEdit.setBounds(130, 240, 200, 30);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Email");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(130, 220, 37, 16);

        txtCargoFuncEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtCargoFuncEdit.setBorder(null);
        txtCargoFuncEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoFuncEditActionPerformed(evt);
            }
        });
        jPanel3.add(txtCargoFuncEdit);
        txtCargoFuncEdit.setBounds(440, 110, 200, 30);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cargo");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(440, 90, 37, 16);

        txtSalarioFuncEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtSalarioFuncEdit.setBorder(null);
        txtSalarioFuncEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioFuncEditActionPerformed(evt);
            }
        });
        jPanel3.add(txtSalarioFuncEdit);
        txtSalarioFuncEdit.setBounds(440, 170, 200, 30);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Salario");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(440, 150, 37, 16);

        btnUpdateFunc.setBackground(new java.awt.Color(0, 255, 0));
        btnUpdateFunc.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateFunc.setText("Salvar Alateração");
        btnUpdateFunc.setToolTipText("");
        btnUpdateFunc.setBorder(null);
        btnUpdateFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFuncActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdateFunc);
        btnUpdateFunc.setBounds(430, 310, 180, 40);

        btnDeleteFunc.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteFunc.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFunc.setText("Apagar Funcionario");
        btnDeleteFunc.setBorder(null);
        btnDeleteFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFuncActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteFunc);
        btnDeleteFunc.setBounds(190, 310, 180, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 740, 390);

        setSize(new java.awt.Dimension(752, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void getFuncEdit(Funcionario func) {
        txtNomeFuncEdit.setText(func.getNome());
        txtEmailFuncEdit.setText(func.getEmail());
        txtCpfFuncEdit.setText(func.getCpf());
        txtCargoFuncEdit.setText(func.getCargo());
        txtSalarioFuncEdit.setText(String.valueOf(func.getSalario()));
    }
    
    private void txtFuncNomeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncNomeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncNomeEditActionPerformed

    private void txtFuncCPFEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncCPFEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncCPFEditActionPerformed

    private void txtFuncNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncNome2ActionPerformed

    private void txtFuncEmailEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncEmailEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncEmailEditActionPerformed

    private void txtFuncNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncNome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncNome4ActionPerformed

    private void txtFuncCargoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncCargoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncCargoEditActionPerformed

    private void txtFuncSalarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncSalarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncSalarioEditActionPerformed

    private void txtFuncNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncNomeActionPerformed

    private void txtNomeFuncEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncEditActionPerformed

    private void txtCpfFuncEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfFuncEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfFuncEditActionPerformed

    private void txtEmailFuncEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFuncEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFuncEditActionPerformed

    private void txtCargoFuncEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoFuncEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoFuncEditActionPerformed

    private void txtSalarioFuncEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioFuncEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioFuncEditActionPerformed

    private void btnDeleteFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFuncActionPerformed
        this.conectar.conectaBanco();
        
        try {
            this.conectar.updateSQL("delete from funcionarios where funcionario_cpf = "+"'"+txtCpfFuncEdit.getText()+"';");
            JOptionPane.showMessageDialog (null, "Funcionario apagado do banco de dados", "Apagado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnDeleteFuncActionPerformed

    private void btnUpdateFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFuncActionPerformed
        this.conectar.conectaBanco();
        
        try {
            this.conectar.updateSQL("update funcionarios set funcionario_email ="+"'"+txtEmailFuncEdit.getText()+"', funcionario_cargo ="+"'"+txtCargoFuncEdit.getText()+"',funcionario_salario ="+"'"+txtSalarioFuncEdit.getText()+"' where funcionario_cpf = "+"'"+txtCpfFuncEdit.getText()+"';");
            JOptionPane.showMessageDialog (null, "Editado Funcionario editado do banco de dados", "Editado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnUpdateFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFuncScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFuncScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFuncScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFuncScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFuncScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDeleteFunc;
    private javax.swing.JToggleButton btnUpdateFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField txtCargoFuncEdit;
    private javax.swing.JTextField txtCpfFuncEdit;
    private javax.swing.JTextField txtEmailFuncEdit;
    private javax.swing.JTextField txtFuncCPFEdit;
    private javax.swing.JTextField txtFuncCargoEdit;
    private javax.swing.JTextField txtFuncEmailEdit;
    private javax.swing.JTextField txtFuncNome;
    private javax.swing.JTextField txtFuncNome2;
    private javax.swing.JTextField txtFuncNome4;
    private javax.swing.JTextField txtFuncNomeEdit;
    private javax.swing.JTextField txtFuncSalarioEdit;
    private javax.swing.JTextField txtNomeFuncEdit;
    private javax.swing.JTextField txtSalarioFuncEdit;
    // End of variables declaration//GEN-END:variables
}
