/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexoes.MySQL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Alocacao;
import objetos.Empresa;

/**
 *
 * @author gabri
 */
public class EditAlocatScreen extends javax.swing.JFrame {

    /**
     * Creates new form EditEmpresaScreen
     */
    public EditAlocatScreen() {
        initComponents();
        puxarListaEmpresa();
        puxarListaFuncionarios();
        popularComboEmpresa();
        popularComboFunc();
    }
    
    public String alo_id = "";
    
    ArrayList<EmpresaAlocacao> listaEmpresa = new ArrayList<EmpresaAlocacao>();
    ArrayList<FuncAlocacao> listaFunc = new ArrayList<FuncAlocacao>();
    
    MySQL conectar = new MySQL("localhost:3306","brunoac2","root","123mudar");
    
    private class EmpresaAlocacao {
        String razaoSocial,id;
    }
    
    private class FuncAlocacao {
        String nome,id;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTipoLocacao = new javax.swing.JTextField();
        comboLocacaoEmpresa = new javax.swing.JComboBox<>();
        btnSalvarAlocacao = new javax.swing.JButton();
        comboLocacaoFunc = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDetalhesLocacao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtQtdHorasLocacao = new javax.swing.JTextField();
        btnDeleteEmpresa = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Quantidade de horas");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Tipo de serviço");

        txtTipoLocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtTipoLocacao.setBorder(null);

        comboLocacaoEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        comboLocacaoEmpresa.setEditable(true);
        comboLocacaoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        comboLocacaoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocacaoEmpresaActionPerformed(evt);
            }
        });

        btnSalvarAlocacao.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarAlocacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarAlocacao.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarAlocacao.setText("Cadastrar");
        btnSalvarAlocacao.setBorder(null);
        btnSalvarAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlocacaoActionPerformed(evt);
            }
        });

        comboLocacaoFunc.setBackground(new java.awt.Color(204, 204, 204));
        comboLocacaoFunc.setEditable(true);
        comboLocacaoFunc.setForeground(new java.awt.Color(255, 255, 255));
        comboLocacaoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocacaoFuncActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Funcionario");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Empresa");

        txtDetalhesLocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtDetalhesLocacao.setBorder(null);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Detalhes");

        txtQtdHorasLocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtQtdHorasLocacao.setBorder(null);

        btnDeleteEmpresa.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEmpresa.setText("Apagar Alocacao");
        btnDeleteEmpresa.setBorder(null);
        btnDeleteEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboLocacaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(comboLocacaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtQtdHorasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetalhesLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnDeleteEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnSalvarAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDetalhesLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocacaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdHorasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocacaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboLocacaoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocacaoFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocacaoFuncActionPerformed

    private void btnSalvarAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlocacaoActionPerformed
        this.conectar.conectaBanco();
        
        try {
            
            String id_func = listaFunc.get(comboLocacaoFunc.getSelectedIndex()).id;
            String id_empresa = listaEmpresa.get(comboLocacaoEmpresa.getSelectedIndex()).id;
            
            this.conectar.updateSQL("UPDATE alocacao set alocacao_prestador_id ='"+id_func+"', alocacao_empresa_id ='"+id_empresa+"' ,alocacao_detalhes ='"+txtDetalhesLocacao.getText()+"', alocacao_quantidade_horas ='"+txtQtdHorasLocacao.getText()+"', alocacao_tipo_servico ='"+txtTipoLocacao.getText()+"' where alocacao_id = '"+this.alo_id+"'");
            
            JOptionPane.showMessageDialog (null, "Alocacao editada no banco de dados", "Editada", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnSalvarAlocacaoActionPerformed

    private void comboLocacaoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocacaoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocacaoEmpresaActionPerformed

    private void btnDeleteEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpresaActionPerformed
        this.conectar.conectaBanco();
        try {
            this.conectar.updateSQL("DELETE from alocacao where alocacao_id ='"+this.alo_id+"';");
            JOptionPane.showMessageDialog (null, "Alocacao apagada do banco de dados", "Apagado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnDeleteEmpresaActionPerformed
        
    private boolean validarCamposEmpresa() {
        return true;
    }
    
    public void configCampos(Alocacao novaAlocacao) {
        for (int i = 0; i < listaEmpresa.size(); i++) {
            if(listaEmpresa.get(i).id.equals(novaAlocacao.getEmpresa_id())) {
                comboLocacaoEmpresa.setSelectedIndex(i);
            }
        }
        for (int i = 0; i < listaFunc.size(); i++) {
            if(listaFunc.get(i).id.equals(novaAlocacao.getFunc_id())) {
                comboLocacaoFunc.setSelectedIndex(i);
            }
        }
        txtDetalhesLocacao.setText(novaAlocacao.getDetalhes());
        txtQtdHorasLocacao.setText(novaAlocacao.getQuantidades_horas());
        txtTipoLocacao.setText(novaAlocacao.getTipo_servico());
    }
    
    private void puxarListaEmpresa() {
        this.conectar.conectaBanco();
        
        try {
            this.conectar.executarSQL("SELECT empresa_razao_social,empresa_id from empresa");
            while(this.conectar.getResultSet().next()) {
               EmpresaAlocacao empresaDados = new EmpresaAlocacao();
                empresaDados.razaoSocial = this.conectar.getResultSet().getString(1);
                empresaDados.id = this.conectar.getResultSet().getString(2);
                listaEmpresa.add(empresaDados);
            }
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }
    
    private void puxarListaFuncionarios() {
        this.conectar.conectaBanco();
        
        try {
            this.conectar.executarSQL("SELECT funcionario_nome,funcionario_id from funcionarios");
            while(this.conectar.getResultSet().next()) {
                FuncAlocacao funcDados = new FuncAlocacao();
                funcDados.nome = this.conectar.getResultSet().getString(1);
                funcDados.id = this.conectar.getResultSet().getString(2);
                listaFunc.add(funcDados);
            }
        } catch (Exception e) {
        } finally {
            this.conectar.fechaBanco();
        }
    }
    
    private void popularComboEmpresa() {
        for (int i = 0; i < listaEmpresa.size(); i++) {
            comboLocacaoEmpresa.addItem(listaEmpresa.get(i).razaoSocial);
        }
    }
    
    private void popularComboFunc() {
        for (int i = 0; i < listaFunc.size(); i++) {
            comboLocacaoFunc.addItem(listaFunc.get(i).nome);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAlocatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAlocatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAlocatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAlocatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAlocatScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDeleteEmpresa;
    private javax.swing.JButton btnSalvarAlocacao;
    private javax.swing.JComboBox<String> comboLocacaoEmpresa;
    private javax.swing.JComboBox<String> comboLocacaoFunc;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDetalhesLocacao;
    private javax.swing.JTextField txtQtdHorasLocacao;
    private javax.swing.JTextField txtTipoLocacao;
    // End of variables declaration//GEN-END:variables
}
