/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexoes.MySQL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Alocacao;
import objetos.Empresa;
import objetos.Funcionario;
import objetos.Usuario;

/**
 *
 * @author gabri
 */
public class MenuScreen extends javax.swing.JFrame {

    /**
     * Creates new form MenuScreen
     */
    public MenuScreen() {
        initComponents();
        puxarListaEmpresa();
        puxarListaFuncionarios();
        popularComboEmpresa();
        popularComboFunc();
    }
    Usuario usuario = new Usuario();
    MySQL conectar = new MySQL("localhost:3306","brunoac2","root","123mudar");
    ArrayList<EmpresaAlocacao> listaEmpresa = new ArrayList<EmpresaAlocacao>();
    ArrayList<FuncAlocacao> listaFunc = new ArrayList<FuncAlocacao>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Consultar = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        txtFuncNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFuncCpf = new javax.swing.JTextField();
        txtFuncEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFuncCargo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFuncSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrarFunc = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtConsultaFunc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConsultarFunc = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        txtUsernamePage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSenhaPage = new javax.swing.JTextField();
        btnDeleteUser = new javax.swing.JToggleButton();
        btnUpdateUsuser = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtRazaoSocialEmpresa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCnpjEmpresa = new javax.swing.JTextField();
        txtEnderecoEmpresa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCadastrarEmpresa = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtConsultaEmpresa = new javax.swing.JTextField();
        btnConsultarEmpresa = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        comboLocacaoEmpresa = new javax.swing.JComboBox<>();
        comboLocacaoFunc = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDetalhesLocacao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtQtdHorasLocacao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTipoLocacao = new javax.swing.JTextField();
        btnCadastrarAlocacao = new javax.swing.JButton();
        btnCadastrarAlocacao1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnConsultarEmpresa1 = new javax.swing.JToggleButton();
        txtConsultaAlocacao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Consultar.setBackground(new java.awt.Color(0, 0, 0));
        Consultar.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        txtFuncNome.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncNome.setBorder(null);
        txtFuncNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncNomeActionPerformed(evt);
            }
        });
        jPanel5.add(txtFuncNome);
        txtFuncNome.setBounds(170, 80, 200, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(170, 60, 37, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CPF");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(170, 130, 37, 16);

        txtFuncCpf.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncCpf.setBorder(null);
        jPanel5.add(txtFuncCpf);
        txtFuncCpf.setBounds(170, 150, 200, 30);

        txtFuncEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncEmail.setBorder(null);
        jPanel5.add(txtFuncEmail);
        txtFuncEmail.setBounds(170, 220, 200, 30);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(170, 200, 37, 16);

        txtFuncCargo.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncCargo.setBorder(null);
        txtFuncCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncCargoActionPerformed(evt);
            }
        });
        jPanel5.add(txtFuncCargo);
        txtFuncCargo.setBounds(490, 90, 200, 30);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cargo");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(490, 70, 37, 16);

        txtFuncSalario.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncSalario.setBorder(null);
        jPanel5.add(txtFuncSalario);
        txtFuncSalario.setBounds(490, 150, 200, 30);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Salario");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(490, 130, 80, 16);

        btnCadastrarFunc.setBackground(new java.awt.Color(0, 255, 0));
        btnCadastrarFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarFunc.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarFunc.setText("Cadastrar");
        btnCadastrarFunc.setBorder(null);
        btnCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncActionPerformed(evt);
            }
        });
        jPanel5.add(btnCadastrarFunc);
        btnCadastrarFunc.setBounds(310, 310, 240, 40);

        Consultar.addTab("Cadastrar Funcionario", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        txtConsultaFunc.setBackground(new java.awt.Color(204, 204, 204));
        txtConsultaFunc.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaFunc.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Coloque o cpf do funcionario que deseja consultar");

        btnConsultarFunc.setBackground(new java.awt.Color(0, 255, 51));
        btnConsultarFunc.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarFunc.setText("Consultar");
        btnConsultarFunc.setBorder(null);
        btnConsultarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnConsultarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtConsultaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnConsultarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        Consultar.addTab("Consultar Funcionario", jPanel6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        txtUsernamePage.setBackground(new java.awt.Color(204, 204, 204));
        txtUsernamePage.setBorder(null);
        jPanel3.add(txtUsernamePage);
        txtUsernamePage.setBounds(230, 120, 200, 30);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Username");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(230, 100, 70, 16);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Senha");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(490, 100, 37, 16);

        txtSenhaPage.setBackground(new java.awt.Color(204, 204, 204));
        txtSenhaPage.setBorder(null);
        jPanel3.add(txtSenhaPage);
        txtSenhaPage.setBounds(480, 120, 200, 30);

        btnDeleteUser.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("Apagar meu usuario");
        btnDeleteUser.setBorder(null);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteUser);
        btnDeleteUser.setBounds(230, 250, 200, 40);

        btnUpdateUsuser.setBackground(new java.awt.Color(0, 255, 0));
        btnUpdateUsuser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUsuser.setText("Salvar Alateração");
        btnUpdateUsuser.setToolTipText("");
        btnUpdateUsuser.setBorder(null);
        btnUpdateUsuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUsuserActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdateUsuser);
        btnUpdateUsuser.setBounds(480, 250, 200, 40);

        Consultar.addTab("Meu Perfil", jPanel3);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtRazaoSocialEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        txtRazaoSocialEmpresa.setBorder(null);
        txtRazaoSocialEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoSocialEmpresaActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Razao Social");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cnpj");

        txtCnpjEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        txtCnpjEmpresa.setBorder(null);

        txtEnderecoEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        txtEnderecoEmpresa.setBorder(null);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Endereco");

        btnCadastrarEmpresa.setBackground(new java.awt.Color(0, 255, 0));
        btnCadastrarEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarEmpresa.setText("Cadastrar");
        btnCadastrarEmpresa.setBorder(null);
        btnCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRazaoSocialEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnpjEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnderecoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addComponent(btnCadastrarEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(345, 345, 345))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(txtRazaoSocialEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(txtCnpjEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(txtEnderecoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnCadastrarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Consultar.addTab("Cadastrar Empresa", jPanel4);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Coloque o cnpj da empresa que deseja consultar");

        txtConsultaEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        txtConsultaEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaEmpresa.setBorder(null);

        btnConsultarEmpresa.setBackground(new java.awt.Color(0, 255, 51));
        btnConsultarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarEmpresa.setText("Consultar");
        btnConsultarEmpresa.setBorder(null);
        btnConsultarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnConsultarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(201, 201, 201))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnConsultarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Consultar.addTab("Consultar Empresa", jPanel7);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        comboLocacaoEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        comboLocacaoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        comboLocacaoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocacaoEmpresaActionPerformed(evt);
            }
        });

        comboLocacaoFunc.setBackground(new java.awt.Color(204, 204, 204));
        comboLocacaoFunc.setForeground(new java.awt.Color(255, 255, 255));
        comboLocacaoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocacaoFuncActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Funcionario");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Empresa");

        txtDetalhesLocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtDetalhesLocacao.setBorder(null);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Detalhes");

        txtQtdHorasLocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtQtdHorasLocacao.setBorder(null);

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Quantidade de horas");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Tipo de serviço");

        txtTipoLocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtTipoLocacao.setBorder(null);

        btnCadastrarAlocacao.setBackground(new java.awt.Color(0, 255, 0));
        btnCadastrarAlocacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarAlocacao.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAlocacao.setText("Cadastrar");
        btnCadastrarAlocacao.setBorder(null);
        btnCadastrarAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlocacaoActionPerformed(evt);
            }
        });

        btnCadastrarAlocacao1.setBackground(new java.awt.Color(102, 204, 255));
        btnCadastrarAlocacao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarAlocacao1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAlocacao1.setText("Atualizar");
        btnCadastrarAlocacao1.setBorder(null);
        btnCadastrarAlocacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlocacao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboLocacaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(comboLocacaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarAlocacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtQtdHorasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetalhesLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(btnCadastrarAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDetalhesLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocacaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdHorasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocacaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnCadastrarAlocacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(txtTipoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnCadastrarAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Consultar.addTab("Cadastrar Alocação", jPanel8);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        btnConsultarEmpresa1.setBackground(new java.awt.Color(0, 255, 51));
        btnConsultarEmpresa1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarEmpresa1.setText("Consultar");
        btnConsultarEmpresa1.setBorder(null);
        btnConsultarEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpresa1ActionPerformed(evt);
            }
        });

        txtConsultaAlocacao.setBackground(new java.awt.Color(204, 204, 204));
        txtConsultaAlocacao.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaAlocacao.setBorder(null);
        txtConsultaAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaAlocacaoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Coloque o id que deseja consultar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnConsultarEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtConsultaAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(201, 201, 201))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultaAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnConsultarEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Consultar.addTab("Consultar Alocação", jPanel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Consultar)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(969, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private class EmpresaAlocacao {
        String razaoSocial,id;
    }
    
    private void apgarCombo() {
        comboLocacaoEmpresa.removeAllItems();
        comboLocacaoFunc.removeAllItems();
        listaFunc.clear();
        listaEmpresa.clear();
    }
    
    private class FuncAlocacao {
        String nome,id;
    }
    
    private void puxarListaEmpresa() {
        this.conectar.conectaBanco();
        
        try {
            this.conectar.executarSQL("SELECT empresa_razao_social,empresa_id from empresa");
            while(this.conectar.getResultSet().next()) {
                EmpresaAlocacao empresaDados = new EmpresaAlocacao();
                empresaDados.razaoSocial = this.conectar.getResultSet().getString(1);
                empresaDados.id = this.conectar.getResultSet().getString(2);
                listaEmpresa.add(empresaDados);
            }
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }
    
    private void puxarListaFuncionarios() {
        this.conectar.conectaBanco();
        
        try {
            this.conectar.executarSQL("SELECT funcionario_nome,funcionario_id from funcionarios");
            while(this.conectar.getResultSet().next()) {
                FuncAlocacao funcDados = new FuncAlocacao();
                funcDados.nome = this.conectar.getResultSet().getString(1);
                funcDados.id = this.conectar.getResultSet().getString(2);
                listaFunc.add(funcDados);
            }
        } catch (Exception e) {
        } finally {
            this.conectar.fechaBanco();
        }
    }
    
    private void popularComboEmpresa() {
        for (int i = 0; i < listaEmpresa.size(); i++) {
            comboLocacaoEmpresa.addItem(listaEmpresa.get(i).razaoSocial);
        }
    }
    
    private void popularComboFunc() {
        for (int i = 0; i < listaFunc.size(); i++) {
            comboLocacaoFunc.addItem(listaFunc.get(i).nome);
        }
    }
    
    public void entrarUser(Usuario user) {
        
        usuario.setNome(user.getNome());
        usuario.setSenha(user.getSenha());
        
        txtUsernamePage.setText(usuario.getNome());
        txtSenhaPage.setText(usuario.getSenha());
    }
    
    private boolean validarCamposEmpresa() {
        if(txtCnpjEmpresa.getText().length() == 14 && txtEnderecoEmpresa.getText().length() > 0 && txtRazaoSocialEmpresa.getText().length() > 0 ) {
            return true;
        }
        return false;
    }
    
    private boolean validarCampos() {
        if(txtFuncCargo.getText().length() == 0 || 
                txtFuncCpf.getText().length() != 11 || 
                txtFuncEmail.getText().length() == 0 || 
                txtFuncNome.getText().length() == 0 ||
                Integer.parseInt(txtFuncSalario.getText()) <= 0) 
        {
            JOptionPane.showMessageDialog(null, "Error!",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
        
    private boolean valdarCampoLocacao() {
        if(Integer.parseInt(txtQtdHorasLocacao.getText()) > 0 && txtQtdHorasLocacao.getText().length() != 0 && txtTipoLocacao.getText().length() > 0 && txtDetalhesLocacao.getText().length() > 0 ) {
            return true;
        }
        return false;
    }
    
    private void btnConsultarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFuncActionPerformed
        if(txtConsultaFunc.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
            "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            Funcionario consultadoFunc = new Funcionario();
            this.conectar.conectaBanco();
            try {
                this.conectar.executarSQL("SELECT funcionario_nome,funcionario_cpf,funcionario_email,funcionario_cargo,funcionario_salario from funcionarios where funcionario_cpf = "+ "'" + txtConsultaFunc.getText()+ "'" + ";");
                while(this.conectar.getResultSet().next()) {
                    consultadoFunc.setNome(this.conectar.getResultSet().getString(1));
                    consultadoFunc.setCpf(this.conectar.getResultSet().getString(2));
                    consultadoFunc.setEmail(this.conectar.getResultSet().getString(3));
                    consultadoFunc.setCargo(this.conectar.getResultSet().getString(4));
                    consultadoFunc.setSalario(Integer.parseInt(this.conectar.getResultSet().getString(5)));
                }
                System.out.println(consultadoFunc.getNome());
                if(consultadoFunc.getNome() == null) {
                    JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                }
                
                else {
                    EditFuncScreen telaEditFunc = new EditFuncScreen();
                    telaEditFunc.getFuncEdit(consultadoFunc);
                    telaEditFunc.setVisible(true);
                    txtConsultaFunc.setText("");
                }
            } catch (Exception e) {
            } finally {
                this.conectar.fechaBanco();
            }
        }
        
    }//GEN-LAST:event_btnConsultarFuncActionPerformed

    private void txtFuncNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncNomeActionPerformed

    private void txtFuncCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncCargoActionPerformed

    private void btnCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncActionPerformed
        if(this.validarCampos()) {
            this.conectar.conectaBanco();
            Funcionario funcionario = new Funcionario();
            funcionario.setNome(txtFuncNome.getText());
            funcionario.setCpf(txtFuncCpf.getText());
            funcionario.setEmail(txtFuncEmail.getText());
            funcionario.setCargo(txtFuncCargo.getText());
            funcionario.setSalario(Integer.parseInt(txtFuncSalario.getText()));
            
            try {
                this.conectar.insertSQL("INSERT INTO funcionarios values("+null+",'"+funcionario.getNome()+"','"
                    +funcionario.getCpf()+"','"
                    +funcionario.getEmail()+"','"
                    +funcionario.getCargo()+"','"
                    +funcionario.getSalario()+"');");
                
                JOptionPane.showMessageDialog (null, "Cadastrado com sucesso", "Novo Funcionario", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error ! Verifique os dados inseridos",
                "ERR!", JOptionPane.ERROR_MESSAGE);
            } finally {
                this.conectar.fechaBanco();
            }
        }
    }//GEN-LAST:event_btnCadastrarFuncActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
       this.conectar.conectaBanco();
       
        try {
            this.conectar.updateSQL("delete from usuarios where usuario_username = "+"'"+this.usuario.getNome()+"';");
            JOptionPane.showMessageDialog (null, "Apagado", "Usuario apagado do banco de dados", JOptionPane.INFORMATION_MESSAGE);
            new LoginScreen().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnUpdateUsuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUsuserActionPerformed
       this.conectar.conectaBanco();
        
        try {
            this.conectar.updateSQL("update usuarios set usuario_username ="+"'"+txtUsernamePage.getText()+"', usuario_senha ="+"'"+txtSenhaPage.getText()+"' where usuario_username ="+"'"+txtUsernamePage.getText()+"';");
            JOptionPane.showMessageDialog (null, "Editado", "Usuario editado no banco de dados", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnUpdateUsuserActionPerformed

    private void btnConsultarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpresaActionPerformed
        if(txtConsultaEmpresa.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
            "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            Empresa novoEmpresa = new Empresa();
            this.conectar.conectaBanco();
            try {
                this.conectar.executarSQL("SELECT empresa_cnpj,empresa_razao_social,empresa_endereco from empresa where empresa_cnpj = "+ "'" + txtConsultaEmpresa.getText()+ "'" + ";");
                while(this.conectar.getResultSet().next()) {
                    novoEmpresa.setCnpj(this.conectar.getResultSet().getString(1));
                    novoEmpresa.setRazaoSocial(this.conectar.getResultSet().getString(2));
                    novoEmpresa.setEndereco(this.conectar.getResultSet().getString(3));
                }
                if(novoEmpresa.getCnpj() == null) {
                    JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                }
                
                else {
                    EditEmprScreen telaEditEmpresa = new EditEmprScreen();
                    telaEditEmpresa.configCampos(novoEmpresa);
                    telaEditEmpresa.setVisible(true);
                    txtConsultaFunc.setText("");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
                "Error!", JOptionPane.ERROR_MESSAGE);
            } finally {
                this.conectar.fechaBanco();
            }
        }
    }//GEN-LAST:event_btnConsultarEmpresaActionPerformed

    private void txtRazaoSocialEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoSocialEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaoSocialEmpresaActionPerformed

    private void btnCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEmpresaActionPerformed
        this.conectar.conectaBanco();
        
        if(this.validarCamposEmpresa()) {
            try {
                Empresa novaEmpresa = new Empresa();
                
                novaEmpresa.setCnpj(txtCnpjEmpresa.getText());
                novaEmpresa.setEndereco(txtEnderecoEmpresa.getText());
                novaEmpresa.setRazaoSocial(txtRazaoSocialEmpresa.getText());
                
                this.conectar.insertSQL("INSERT into empresa values("+null+",'"+novaEmpresa.getCnpj()+"','"+novaEmpresa.getRazaoSocial()+"','"+novaEmpresa.getEndereco()+"');");
                JOptionPane.showMessageDialog (null, "Empresa Cadastrada com sucesso", "Cadastrada", JOptionPane.INFORMATION_MESSAGE);
                
                txtCnpjEmpresa.setText("");
                txtEnderecoEmpresa.setText("");
                txtRazaoSocialEmpresa.setText("");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error",
                "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            } finally {
                this.conectar.fechaBanco();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarEmpresaActionPerformed

    private void btnCadastrarAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlocacaoActionPerformed
        if(this.valdarCampoLocacao()) {
            this.conectar.conectaBanco();
            
            try {
                String idFunc = listaFunc.get(comboLocacaoFunc.getSelectedIndex()).id;
                String idEmpresa = listaEmpresa.get(comboLocacaoEmpresa.getSelectedIndex()).id;
                
                Alocacao novaAlocacao = new Alocacao();
                
                novaAlocacao.setEmpresa_id(idEmpresa);
                novaAlocacao.setFunc_id(idFunc);
                novaAlocacao.setQuantidades_horas(txtQtdHorasLocacao.getText());
                novaAlocacao.setDetalhes(txtDetalhesLocacao.getText());
                novaAlocacao.setTipo_servico(txtTipoLocacao.getText());
                
                System.out.println(novaAlocacao.getFunc_id());
                this.conectar.insertSQL("INSERT into alocacao values("+null+",'"+novaAlocacao.getFunc_id()+"','"+novaAlocacao.getEmpresa_id()+"'"+",'"+novaAlocacao.getDetalhes()+"','"+novaAlocacao.getQuantidades_horas()+"','"+novaAlocacao.getTipo_servico()+"');");
                JOptionPane.showMessageDialog (null, "Cadastrada com sucesso", "Nova Alocação", JOptionPane.INFORMATION_MESSAGE);
                
                comboLocacaoEmpresa.setSelectedIndex(1);
                comboLocacaoFunc.setSelectedIndex(1);
                txtDetalhesLocacao.setText("");
                txtQtdHorasLocacao.setText("");
                txtTipoLocacao.setText("");
                
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error ! Verifique os dados inseridos",
                "ERR!", JOptionPane.ERROR_MESSAGE);
            } finally {
                this.conectar.fechaBanco();
            }
        }
    }//GEN-LAST:event_btnCadastrarAlocacaoActionPerformed

    private void comboLocacaoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocacaoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocacaoEmpresaActionPerformed

    private void comboLocacaoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocacaoFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocacaoFuncActionPerformed

    private void btnConsultarEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpresa1ActionPerformed
         if(txtConsultaAlocacao.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
            "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            Alocacao consultadoFunc = new Alocacao();
            this.conectar.conectaBanco();
            try {
                this.conectar.executarSQL("SELECT alocacao_prestador_id,alocacao_empresa_id,alocacao_detalhes,alocacao_quantidade_horas,alocacao_tipo_servico from alocacao where alocacao_id = "+ "'" + txtConsultaAlocacao.getText()+ "'" + ";");
                while(this.conectar.getResultSet().next()) {
                    consultadoFunc.setFunc_id(this.conectar.getResultSet().getString(1));
                    consultadoFunc.setEmpresa_id(this.conectar.getResultSet().getString(2));
                    consultadoFunc.setDetalhes(this.conectar.getResultSet().getString(3));
                    consultadoFunc.setQuantidades_horas(this.conectar.getResultSet().getString(4));
                    consultadoFunc.setTipo_servico(this.conectar.getResultSet().getString(5));
                }

                if(consultadoFunc.getFunc_id() == null) {
                    JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                }
                
                else {
                    EditAlocatScreen telaEditAlo = new EditAlocatScreen();
                    telaEditAlo.configCampos(consultadoFunc);
                    telaEditAlo.alo_id = txtConsultaAlocacao.getText();
                    telaEditAlo.setVisible(true);
                    txtConsultaAlocacao.setText("");
                }
            } catch (Exception e) {
            } finally {
                this.conectar.fechaBanco();
            }
        }
    }//GEN-LAST:event_btnConsultarEmpresa1ActionPerformed

    private void txtConsultaAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaAlocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaAlocacaoActionPerformed

    private void btnCadastrarAlocacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlocacao1ActionPerformed
        this.apgarCombo();
        this.puxarListaEmpresa();
        this.puxarListaFuncionarios();
        this.popularComboEmpresa();
        this.popularComboFunc();
    }//GEN-LAST:event_btnCadastrarAlocacao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Consultar;
    private javax.swing.JButton btnCadastrarAlocacao;
    private javax.swing.JButton btnCadastrarAlocacao1;
    private javax.swing.JButton btnCadastrarEmpresa;
    private javax.swing.JButton btnCadastrarFunc;
    private javax.swing.JToggleButton btnConsultarEmpresa;
    private javax.swing.JToggleButton btnConsultarEmpresa1;
    private javax.swing.JToggleButton btnConsultarFunc;
    private javax.swing.JToggleButton btnDeleteUser;
    private javax.swing.JToggleButton btnUpdateUsuser;
    private javax.swing.JComboBox<String> comboLocacaoEmpresa;
    private javax.swing.JComboBox<String> comboLocacaoFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtCnpjEmpresa;
    private javax.swing.JTextField txtConsultaAlocacao;
    private javax.swing.JTextField txtConsultaEmpresa;
    private javax.swing.JTextField txtConsultaFunc;
    private javax.swing.JTextField txtDetalhesLocacao;
    private javax.swing.JTextField txtEnderecoEmpresa;
    private javax.swing.JTextField txtFuncCargo;
    private javax.swing.JTextField txtFuncCpf;
    private javax.swing.JTextField txtFuncEmail;
    private javax.swing.JTextField txtFuncNome;
    private javax.swing.JTextField txtFuncSalario;
    private javax.swing.JTextField txtQtdHorasLocacao;
    private javax.swing.JTextField txtRazaoSocialEmpresa;
    private javax.swing.JTextField txtSenhaPage;
    private javax.swing.JTextField txtTipoLocacao;
    private javax.swing.JTextField txtUsernamePage;
    // End of variables declaration//GEN-END:variables
}
