/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gabri
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }
    
    
    public void loadingProgressBar() {
        for (int i = 0; i <= 100; i++) {
            progressBarSplash.setValue(i);
            if( i < 33) {
                txtAuxProgressBarSplash.setText("Carregando recursos");
            }
            if( i <66 && i > 33) {
                txtAuxProgressBarSplash.setText("Carregando interface gráfica");
            }
            
            if ( i > 66) {
                txtAuxProgressBarSplash.setText("Carregando banco de dados");
            }
            try {
                Thread.sleep(100);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        this.setVisible(false);
        LoginScreen telaLogin = new LoginScreen();
        telaLogin.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBarSplash = new javax.swing.JProgressBar();
        txtAuxProgressBarSplash = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        progressBarSplash.setForeground(new java.awt.Color(0, 0, 0));
        progressBarSplash.setStringPainted(true);
        jPanel1.add(progressBarSplash);
        progressBarSplash.setBounds(90, 330, 540, 21);

        txtAuxProgressBarSplash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAuxProgressBarSplash.setForeground(new java.awt.Color(0, 0, 0));
        txtAuxProgressBarSplash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAuxProgressBarSplash.setText("carregando");
        txtAuxProgressBarSplash.setToolTipText("");
        jPanel1.add(txtAuxProgressBarSplash);
        txtAuxProgressBarSplash.setBounds(90, 300, 540, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Security Santahme (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 0, 510, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 390);

        setSize(new java.awt.Dimension(726, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        SplashScreen progressBar = new SplashScreen();
        progressBar.setVisible(true);
        progressBar.loadingProgressBar();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBarSplash;
    private javax.swing.JLabel txtAuxProgressBarSplash;
    // End of variables declaration//GEN-END:variables
}
